basePath: /api/v1
definitions:
  api.auth:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  v1.AddArticleForm:
    properties:
      content:
        maxLength: 65535
        type: string
      cover_image_url:
        type: string
      created_by:
        maxLength: 100
        type: string
      desc:
        maxLength: 255
        type: string
      state:
        type: integer
      tag_id:
        minimum: 1
        type: integer
      title:
        maxLength: 100
        type: string
    required:
    - content
    - cover_image_url
    - created_by
    - desc
    - state
    - tag_id
    - title
    type: object
  v1.AddTagForm:
    properties:
      created_by:
        maxLength: 100
        type: string
      name:
        maxLength: 100
        type: string
      state:
        type: integer
    required:
    - created_by
    - name
    - state
    type: object
  v1.EditArticleForm:
    properties:
      content:
        type: string
      cover_image_url:
        type: string
      desc:
        type: string
      id:
        minimum: 1
        type: integer
      modified_by:
        type: string
      state:
        type: integer
      tag_id:
        minimum: 1
        type: integer
      title:
        type: string
    required:
    - id
    - tag_id
    type: object
  v1.EditTagForm:
    properties:
      id:
        minimum: 1
        type: integer
      modified_by:
        maxLength: 100
        type: string
      name:
        maxLength: 100
        type: string
      state:
        type: integer
    required:
    - id
    - modified_by
    - name
    - state
    type: object
  v1.ExportTagForm:
    properties:
      name:
        type: string
      state:
        type: integer
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: go-gin-example API
  version: "1.0"
paths:
  /api/v1/articles:
    get:
      parameters:
      - description: TagID
        in: body
        name: tag_id
        schema:
          type: integer
      - description: State
        in: body
        name: state
        schema:
          type: integer
      - description: CreatedBy
        in: body
        name: created_by
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get multiple articles
    post:
      consumes:
      - application/json
      parameters:
      - description: Add article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/v1.AddArticleForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Add article
  /api/v1/articles/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Delete article
    put:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/v1.EditArticleForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Update article
  /api/v1/articles/poster/generate:
    post:
      parameters:
      - description: ArticleID
        in: path
        name: article_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Generate article poster
  /api/v1/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: Auth
        in: body
        name: auth
        required: true
        schema:
          $ref: '#/definitions/api.auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get Auth
  /api/v1/tags:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get multiple article tags
    post:
      consumes:
      - application/json
      parameters:
      - description: Add tag
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/v1.AddTagForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Add article tag
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Delete article tag
    put:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Edit tag
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/v1.EditTagForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Update article tag
  /api/v1/tags/export:
    post:
      consumes:
      - application/json
      parameters:
      - description: Export tag
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/v1.ExportTagForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Export article tag
  /api/v1/tags/import:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Excel File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Import article tag
swagger: "2.0"
