@baseUrl = http://127.0.0.1:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjA5OGY2YmNkNDYyMWQzNzNjYWRlNGU4MzI2MjdiNGY2IiwicGFzc3dvcmQiOiJjYzAzZTc0N2E2YWZiYmNiZjhiZTc2NjhhY2ZlYmVlNSIsImlzcyI6Imdpbi1ibG9nIiwiZXhwIjoxNzQyMzAwNDk4LCJuYmYiOjE3NDIyODk2OTgsImlhdCI6MTc0MjI4OTY5OH0.gPFrUsGH1pKasZ1bFjxHDbbaP32Bp6yEIn6BXEHm4-g
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjA5OGY2YmNkNDYyMWQzNzNjYWRlNGU4MzI2MjdiNGY2IiwicGFzc3dvcmQiOiJjYzAzZTc0N2E2YWZiYmNiZjhiZTc2NjhhY2ZlYmVlNSIsImlzcyI6Imdpbi1ibG9nIiwiZXhwIjoxNzM3NjIyOTI5LCJuYmYiOjE3Mzc2MTIxMjksImlhdCI6MTczNzYxMjEyOX0.SPIR5PvPLPnB_F2yi83V81ytv88nZEUfXA8VNUXWbFI

### Login
POST {{baseUrl}}/api/v1/auth
Content-Type: application/json

{
    "username": "test",
    "password": "test123"
}

### 获取标签列表
GET {{baseUrl}}/api/v1/tags?state=1
Authorization: {{token}}

### Add new tag
POST {{baseUrl}}/api/v1/tags
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "alan-tag-7",
    "created_by": "test",
    "state": 1
}

### Edit tag
PUT {{baseUrl}}/api/v1/tags/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "updated tag",
    "modified_by": "test",
    "state": 1
}

### 删除标签
DELETE {{baseUrl}}/api/v1/tags/2
Authorization: {{token}}

### Export tags
POST {{baseUrl}}/api/v1/tags/export
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "test",
    "state": 1
}

### 导入标签
POST {{baseUrl}}/api/v1/tags/import
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./test.xlsx
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 获取文章列表
GET {{baseUrl}}/api/v1/articles?state=1&tag_id=3
Authorization: {{token}}

### 获取单个文章
GET {{baseUrl}}/api/v1/articles/6
Authorization: {{token}}

### 新增文章
POST {{baseUrl}}/api/v1/articles
Content-Type: application/json
Authorization: {{token}}

{
    "tag_id": 3,
    "title": "alan-test-article",
    "desc": "这是一篇测试文章",
    "content": "文章内容",
    "created_by": "test",
    "state": 1,
    "cover_image_url": "https://www.baidu.com/test.jpg"
}

### 更新文章
PUT {{baseUrl}}/api/v1/articles/1
Content-Type: application/json
Authorization: {{token}}

{
    "tag_id": 1,
    "title": "更新后的文章",
    "desc": "更新后的描述",
    "content": "更新后的内容",
    "modified_by": "admin",
    "state": 1
}

### 删除文章
DELETE {{baseUrl}}/api/v1/articles/1
Authorization: {{token}}

